spring.http.multipart:
   max-file-size: 3MB
   max-request-size: 3MB

logging.level.fi.csc.virtu.samlxmltooling: DEBUG

my.validator.schemaDir: "/Users/klaalo/Haka/metadata_schema/"
my.validator.federations:
   - Virtu
   - Haka
my.validator.federationSpecs:
   Virtu:
      mdUrl: "https://virtu-ds.csc.fi/fed/virtu/virtu-metadata-v3.xml"
      mdCertFile: "/Users/klaalo/Virtu/virtu-metadata-signing-crt-2015.pem"
      validUntilMin: 27
      validUntilMax: 32
      sigCertValidMin: 30
      sigCertValidMax: 735
      publishFile: "/Users/klaalo/tmp/saml-tooling-folder/intern/virtu-metadata-dev.xml"
      pubScript: "/Users/klaalo/git/saml-xml-metadata-tooling/src/main/sh/publish.sh"
   Haka:
      mdUrl: "https://haka.funet.fi/metadata/haka-metadata.xml"
      mdCertFile: "/Users/klaalo/Haka/haka-sign-v3.pem"
      validUntilMin: 27
      validUntilMax: 32
      sigCertValidMin: 30
      sigCertValidMax: 735
      